spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: yourId
            client-secret: yourSecret
  data:
    cassandra:
      keyspace-name: main
      username: SKYEkLulpccLZOKYpmTZXILl
      password: Qggn9DybZYR5Z5sD7XAHu00gPm+dIC_YlZaYp.Qggn9DybZYR5Z5sD7XAHu00gPm+C3EF8L+Y2_sdrQ8QriUSX1SEd62mqpzdkv.PIo6ZPO+u270U48MZMWFYOgo4_HbOc
      schema-action: create_if_not_exists
      request:
        timeout: 20s
      connection:
        connect-timeout: 20s
        init-query-timeout: 20s
  application:
    name: betterreads

datastax.astra:
  secure-connect-bundle: secure-connect-betterreads.zip

astra:
  db:
    id: e12345a-f123-4ae2-468b-a78104989d15-1
    region: europe-west1
    keyspace: main
    application:
      token: AstraCS:xxxxxxxx:yyyyyyyyyyyy